openapi: 3.0.3
info:
  title: The MailTrap API (https://api-docs.mailtrap.io/)
  version: v2
servers:
  - url: "https://sandbox.api.mailtrap.io"
paths:
  /api/send/{inbox_id}:
    post:
      summary: Send email
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMailDetails'
        required: true
      parameters:
        - name: inbox_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: all good
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMailResponse'
      security:
        - apiToken: []
components:
  schemas:
    SendMailDetails:
      type: object
      properties:
        to:
          type: array
          items:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
        from:
          type: object
          properties:
            email:
              type: string
            name:
              type: string
        subject:
          type: string
          readOnly: true
        html:
          type: string
          readOnly: true
        text:
          type: string
          readOnly: true
      additionalProperties: false
    SendMailResponse:
      type: object
      properties:
        success:
          type: boolean
          readOnly: true
        message_ids:
          type: array
          items:
            type: string
      additionalProperties: false
  securitySchemes:
    apiToken:
      type: apiKey
      in: header
      name: Api-Token
