---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: ticket-events
  namespace: {{ .Values.namespace.name }}
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ticket-closed
  namespace: {{ .Values.namespace.name }}
spec:
  broker: ticket-events
  filter:
    attributes:
      type: dev.parodos.escalation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: {{ .Values.escalationSwf.name }}
---
{{- if .Values.eventdisplay.enabled }}
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
  namespace: {{ .Values.namespace.name }}
spec:
  broker: ticket-events
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
{{- end }}
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: ticket-source
  namespace: {{ .Values.namespace.name }}
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: {{ .Values.jiralistener.name }}
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: ticket-events
      namespace: {{ .Values.namespace.name }}

